/* eslint-disable */
import * as types from './graphql';



/**
 * Map of all GraphQL operations in the project.
 *
 * This map has several performance disadvantages:
 * 1. It is not tree-shakeable, so it will include all operations in the project.
 * 2. It is not minifiable, so the string of a GraphQL query will be multiple times inside the bundle.
 * 3. It does not support dead code elimination, so it will add unused operations.
 *
 * Therefore it is highly recommended to use the babel or swc plugin for production.
 * Learn more about it here: https://the-guild.dev/graphql/codegen/plugins/presets/preset-client#reducing-bundle-size
 */
type Documents = {
    "\n  query Apps($length: Int = 20, $skip: Int = 0) {\n    apps(\n      first: $length\n      skip: $skip\n      orderBy: timestamp\n      orderDirection: desc\n    ) {\n      address: id\n      owner {\n        address: id\n      }\n      timestamp\n      name\n      type\n      multiaddr\n      checksum\n      mrenclave\n      transfers(orderBy: timestamp, orderDirection: desc) {\n        transaction {\n          txHash: id\n          timestamp\n          blockNumber\n        }\n      }\n    }\n  }\n": typeof types.AppsDocument,
    "\n  query NextApps($length: Int = 20, $skip: Int = 0) {\n    apps(\n      first: $length\n      skip: $skip\n      orderBy: timestamp\n      orderDirection: desc\n    ) {\n      address: id\n    }\n  }\n": typeof types.NextAppsDocument,
    "\n  query DatasetDeals($length: Int = 20, $skip: Int = 0, $datasetAddress: ID!) {\n    dataset(id: $datasetAddress) {\n      address: id\n      deals: usages(\n        first: $length\n        skip: $skip\n        orderBy: timestamp\n        orderDirection: desc\n      ) {\n        dealid: id\n        timestamp\n        requester {\n          address: id\n        }\n        beneficiary {\n          address: id\n        }\n        callback {\n          address: id\n        }\n        app {\n          address: id\n          name\n        }\n        dataset {\n          address: id\n          name\n        }\n        workerpool {\n          address: id\n          description\n        }\n        category {\n          catid: id\n          workClockTimeRef\n        }\n        startTime\n        appPrice\n        datasetPrice\n        workerpoolPrice\n        botSize\n        trust\n        completedTasksCount\n        claimedTasksCount\n      }\n    }\n  }\n": typeof types.DatasetDealsDocument,
    "\n  query Dataset($datasetAddress: ID!, $datasetAddressString: String!) {\n    dataset(id: $datasetAddress) {\n      address: id\n      name\n      owner {\n        address: id\n      }\n      multiaddr\n      checksum\n      transfers(\n        where: { dataset: $datasetAddressString }\n        orderBy: timestamp\n        orderDirection: asc\n      ) {\n        dataset {\n          address: id\n        }\n        from {\n          address: id\n        }\n        to {\n          address: id\n        }\n        transaction {\n          txHash: id\n          timestamp\n          blockNumber\n        }\n      }\n    }\n  }\n": typeof types.DatasetDocument,
    "\n  query NextDatasetDeals(\n    $length: Int = 20\n    $skip: Int = 0\n    $datasetAddress: ID!\n  ) {\n    dataset(id: $datasetAddress) {\n      address: id\n      deals: usages(\n        first: $length\n        skip: $skip\n        orderBy: timestamp\n        orderDirection: desc\n      ) {\n        dealid: id\n      }\n    }\n  }\n": typeof types.NextDatasetDealsDocument,
    "\n  query Datasets($length: Int = 20, $skip: Int = 0) {\n    datasets(\n      first: $length\n      skip: $skip\n      orderBy: timestamp\n      orderDirection: desc\n    ) {\n      address: id\n      owner {\n        address: id\n      }\n      timestamp\n      name\n      multiaddr\n      checksum\n      transfers(orderBy: timestamp, orderDirection: desc) {\n        transaction {\n          txHash: id\n          timestamp\n          blockNumber\n        }\n      }\n    }\n  }\n": typeof types.DatasetsDocument,
    "\n  query NextDatasets($length: Int = 20, $skip: Int = 0) {\n    datasets(\n      first: $length\n      skip: $skip\n      orderBy: timestamp\n      orderDirection: desc\n    ) {\n      address: id\n    }\n  }\n": typeof types.NextDatasetsDocument,
    "\n  query Deal($dealAddress: ID!) {\n    deal(id: $dealAddress) {\n      dealid: id\n      timestamp\n      startTime\n      app {\n        address: id\n        name\n      }\n      dataset {\n        address: id\n        name\n      }\n      workerpool {\n        address: id\n        description\n      }\n      beneficiary {\n        address: id\n      }\n      callback {\n        address: id\n      }\n      appPrice\n      datasetPrice\n      workerpoolPrice\n      params\n      tag\n      trust\n      category {\n        catid: id\n        name\n        workClockTimeRef\n        description\n      }\n      botSize\n      botFirst\n      completedTasksCount\n      claimedTasksCount\n      requester {\n        address: id\n      }\n      dealEvents: events(orderBy: timestamp, orderDirection: asc) {\n        timestamp\n        id\n        type: __typename\n        transaction {\n          txHash: id\n        }\n      }\n    }\n  }\n": typeof types.DealDocument,
    "\n  query DealTasks($dealAddress: ID!) {\n    deal(id: $dealAddress) {\n      tasks(orderBy: index, orderDirection: asc) {\n        taskid: id\n        index\n        status\n        finalDeadline\n      }\n    }\n  }\n": typeof types.DealTasksDocument,
    "\n  query Deals($length: Int = 20, $skip: Int = 0) {\n    deals(\n      first: $length\n      skip: $skip\n      orderBy: timestamp\n      orderDirection: desc\n    ) {\n      dealid: id\n      timestamp\n      requester {\n        address: id\n      }\n      beneficiary {\n        address: id\n      }\n      callback {\n        address: id\n      }\n      app {\n        address: id\n      }\n      dataset {\n        address: id\n      }\n      workerpool {\n        address: id\n      }\n      category {\n        catid: id\n        workClockTimeRef\n      }\n      startTime\n      appPrice\n      datasetPrice\n      workerpoolPrice\n      botSize\n      trust\n      completedTasksCount\n      claimedTasksCount\n    }\n  }\n": typeof types.DealsDocument,
    "\n  query NextDeals($length: Int = 20, $skip: Int = 0) {\n    deals(\n      first: $length\n      skip: $skip\n      orderBy: timestamp\n      orderDirection: desc\n    ) {\n      dealid: id\n    }\n  }\n": typeof types.NextDealsDocument,
    "\n  query NextTasks($length: Int = 20, $skip: Int = 0) {\n    tasks(\n      first: $length\n      skip: $skip\n      orderBy: timestamp\n      orderDirection: desc\n    ) {\n      taskid: id\n    }\n  }\n": typeof types.NextTasksDocument,
    "\n  query Tasks($length: Int = 20, $skip: Int = 0) {\n    tasks(\n      first: $length\n      skip: $skip\n      orderBy: timestamp\n      orderDirection: desc\n    ) {\n      taskid: id\n      index\n      finalDeadline\n      status\n      timestamp\n      deal {\n        requester {\n          address: id\n        }\n        beneficiary {\n          address: id\n        }\n        app {\n          address: id\n        }\n        dataset {\n          address: id\n        }\n        workerpool {\n          address: id\n        }\n        category {\n          catid: id\n          workClockTimeRef\n        }\n      }\n    }\n  }\n": typeof types.TasksDocument,
    "\n  query NextWorkerpools($length: Int = 20, $skip: Int = 0) {\n    workerpools(\n      first: $length\n      skip: $skip\n      orderBy: timestamp\n      orderDirection: desc\n    ) {\n      address: id\n    }\n  }\n": typeof types.NextWorkerpoolsDocument,
    "\n  query Workerpools($length: Int = 20, $skip: Int = 0) {\n    workerpools(\n      first: $length\n      skip: $skip\n      orderBy: timestamp\n      orderDirection: desc\n    ) {\n      address: id\n      owner {\n        address: id\n      }\n      timestamp\n      description\n      workerStakeRatio\n      schedulerRewardRatio\n      transfers(orderBy: timestamp, orderDirection: desc) {\n        transaction {\n          txHash: id\n          timestamp\n          blockNumber\n        }\n      }\n    }\n  }\n": typeof types.WorkerpoolsDocument,
};
const documents: Documents = {
    "\n  query Apps($length: Int = 20, $skip: Int = 0) {\n    apps(\n      first: $length\n      skip: $skip\n      orderBy: timestamp\n      orderDirection: desc\n    ) {\n      address: id\n      owner {\n        address: id\n      }\n      timestamp\n      name\n      type\n      multiaddr\n      checksum\n      mrenclave\n      transfers(orderBy: timestamp, orderDirection: desc) {\n        transaction {\n          txHash: id\n          timestamp\n          blockNumber\n        }\n      }\n    }\n  }\n": types.AppsDocument,
    "\n  query NextApps($length: Int = 20, $skip: Int = 0) {\n    apps(\n      first: $length\n      skip: $skip\n      orderBy: timestamp\n      orderDirection: desc\n    ) {\n      address: id\n    }\n  }\n": types.NextAppsDocument,
    "\n  query DatasetDeals($length: Int = 20, $skip: Int = 0, $datasetAddress: ID!) {\n    dataset(id: $datasetAddress) {\n      address: id\n      deals: usages(\n        first: $length\n        skip: $skip\n        orderBy: timestamp\n        orderDirection: desc\n      ) {\n        dealid: id\n        timestamp\n        requester {\n          address: id\n        }\n        beneficiary {\n          address: id\n        }\n        callback {\n          address: id\n        }\n        app {\n          address: id\n          name\n        }\n        dataset {\n          address: id\n          name\n        }\n        workerpool {\n          address: id\n          description\n        }\n        category {\n          catid: id\n          workClockTimeRef\n        }\n        startTime\n        appPrice\n        datasetPrice\n        workerpoolPrice\n        botSize\n        trust\n        completedTasksCount\n        claimedTasksCount\n      }\n    }\n  }\n": types.DatasetDealsDocument,
    "\n  query Dataset($datasetAddress: ID!, $datasetAddressString: String!) {\n    dataset(id: $datasetAddress) {\n      address: id\n      name\n      owner {\n        address: id\n      }\n      multiaddr\n      checksum\n      transfers(\n        where: { dataset: $datasetAddressString }\n        orderBy: timestamp\n        orderDirection: asc\n      ) {\n        dataset {\n          address: id\n        }\n        from {\n          address: id\n        }\n        to {\n          address: id\n        }\n        transaction {\n          txHash: id\n          timestamp\n          blockNumber\n        }\n      }\n    }\n  }\n": types.DatasetDocument,
    "\n  query NextDatasetDeals(\n    $length: Int = 20\n    $skip: Int = 0\n    $datasetAddress: ID!\n  ) {\n    dataset(id: $datasetAddress) {\n      address: id\n      deals: usages(\n        first: $length\n        skip: $skip\n        orderBy: timestamp\n        orderDirection: desc\n      ) {\n        dealid: id\n      }\n    }\n  }\n": types.NextDatasetDealsDocument,
    "\n  query Datasets($length: Int = 20, $skip: Int = 0) {\n    datasets(\n      first: $length\n      skip: $skip\n      orderBy: timestamp\n      orderDirection: desc\n    ) {\n      address: id\n      owner {\n        address: id\n      }\n      timestamp\n      name\n      multiaddr\n      checksum\n      transfers(orderBy: timestamp, orderDirection: desc) {\n        transaction {\n          txHash: id\n          timestamp\n          blockNumber\n        }\n      }\n    }\n  }\n": types.DatasetsDocument,
    "\n  query NextDatasets($length: Int = 20, $skip: Int = 0) {\n    datasets(\n      first: $length\n      skip: $skip\n      orderBy: timestamp\n      orderDirection: desc\n    ) {\n      address: id\n    }\n  }\n": types.NextDatasetsDocument,
    "\n  query Deal($dealAddress: ID!) {\n    deal(id: $dealAddress) {\n      dealid: id\n      timestamp\n      startTime\n      app {\n        address: id\n        name\n      }\n      dataset {\n        address: id\n        name\n      }\n      workerpool {\n        address: id\n        description\n      }\n      beneficiary {\n        address: id\n      }\n      callback {\n        address: id\n      }\n      appPrice\n      datasetPrice\n      workerpoolPrice\n      params\n      tag\n      trust\n      category {\n        catid: id\n        name\n        workClockTimeRef\n        description\n      }\n      botSize\n      botFirst\n      completedTasksCount\n      claimedTasksCount\n      requester {\n        address: id\n      }\n      dealEvents: events(orderBy: timestamp, orderDirection: asc) {\n        timestamp\n        id\n        type: __typename\n        transaction {\n          txHash: id\n        }\n      }\n    }\n  }\n": types.DealDocument,
    "\n  query DealTasks($dealAddress: ID!) {\n    deal(id: $dealAddress) {\n      tasks(orderBy: index, orderDirection: asc) {\n        taskid: id\n        index\n        status\n        finalDeadline\n      }\n    }\n  }\n": types.DealTasksDocument,
    "\n  query Deals($length: Int = 20, $skip: Int = 0) {\n    deals(\n      first: $length\n      skip: $skip\n      orderBy: timestamp\n      orderDirection: desc\n    ) {\n      dealid: id\n      timestamp\n      requester {\n        address: id\n      }\n      beneficiary {\n        address: id\n      }\n      callback {\n        address: id\n      }\n      app {\n        address: id\n      }\n      dataset {\n        address: id\n      }\n      workerpool {\n        address: id\n      }\n      category {\n        catid: id\n        workClockTimeRef\n      }\n      startTime\n      appPrice\n      datasetPrice\n      workerpoolPrice\n      botSize\n      trust\n      completedTasksCount\n      claimedTasksCount\n    }\n  }\n": types.DealsDocument,
    "\n  query NextDeals($length: Int = 20, $skip: Int = 0) {\n    deals(\n      first: $length\n      skip: $skip\n      orderBy: timestamp\n      orderDirection: desc\n    ) {\n      dealid: id\n    }\n  }\n": types.NextDealsDocument,
    "\n  query NextTasks($length: Int = 20, $skip: Int = 0) {\n    tasks(\n      first: $length\n      skip: $skip\n      orderBy: timestamp\n      orderDirection: desc\n    ) {\n      taskid: id\n    }\n  }\n": types.NextTasksDocument,
    "\n  query Tasks($length: Int = 20, $skip: Int = 0) {\n    tasks(\n      first: $length\n      skip: $skip\n      orderBy: timestamp\n      orderDirection: desc\n    ) {\n      taskid: id\n      index\n      finalDeadline\n      status\n      timestamp\n      deal {\n        requester {\n          address: id\n        }\n        beneficiary {\n          address: id\n        }\n        app {\n          address: id\n        }\n        dataset {\n          address: id\n        }\n        workerpool {\n          address: id\n        }\n        category {\n          catid: id\n          workClockTimeRef\n        }\n      }\n    }\n  }\n": types.TasksDocument,
    "\n  query NextWorkerpools($length: Int = 20, $skip: Int = 0) {\n    workerpools(\n      first: $length\n      skip: $skip\n      orderBy: timestamp\n      orderDirection: desc\n    ) {\n      address: id\n    }\n  }\n": types.NextWorkerpoolsDocument,
    "\n  query Workerpools($length: Int = 20, $skip: Int = 0) {\n    workerpools(\n      first: $length\n      skip: $skip\n      orderBy: timestamp\n      orderDirection: desc\n    ) {\n      address: id\n      owner {\n        address: id\n      }\n      timestamp\n      description\n      workerStakeRatio\n      schedulerRewardRatio\n      transfers(orderBy: timestamp, orderDirection: desc) {\n        transaction {\n          txHash: id\n          timestamp\n          blockNumber\n        }\n      }\n    }\n  }\n": types.WorkerpoolsDocument,
};

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query Apps($length: Int = 20, $skip: Int = 0) {\n    apps(\n      first: $length\n      skip: $skip\n      orderBy: timestamp\n      orderDirection: desc\n    ) {\n      address: id\n      owner {\n        address: id\n      }\n      timestamp\n      name\n      type\n      multiaddr\n      checksum\n      mrenclave\n      transfers(orderBy: timestamp, orderDirection: desc) {\n        transaction {\n          txHash: id\n          timestamp\n          blockNumber\n        }\n      }\n    }\n  }\n"): typeof import('./graphql').AppsDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query NextApps($length: Int = 20, $skip: Int = 0) {\n    apps(\n      first: $length\n      skip: $skip\n      orderBy: timestamp\n      orderDirection: desc\n    ) {\n      address: id\n    }\n  }\n"): typeof import('./graphql').NextAppsDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query DatasetDeals($length: Int = 20, $skip: Int = 0, $datasetAddress: ID!) {\n    dataset(id: $datasetAddress) {\n      address: id\n      deals: usages(\n        first: $length\n        skip: $skip\n        orderBy: timestamp\n        orderDirection: desc\n      ) {\n        dealid: id\n        timestamp\n        requester {\n          address: id\n        }\n        beneficiary {\n          address: id\n        }\n        callback {\n          address: id\n        }\n        app {\n          address: id\n          name\n        }\n        dataset {\n          address: id\n          name\n        }\n        workerpool {\n          address: id\n          description\n        }\n        category {\n          catid: id\n          workClockTimeRef\n        }\n        startTime\n        appPrice\n        datasetPrice\n        workerpoolPrice\n        botSize\n        trust\n        completedTasksCount\n        claimedTasksCount\n      }\n    }\n  }\n"): typeof import('./graphql').DatasetDealsDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query Dataset($datasetAddress: ID!, $datasetAddressString: String!) {\n    dataset(id: $datasetAddress) {\n      address: id\n      name\n      owner {\n        address: id\n      }\n      multiaddr\n      checksum\n      transfers(\n        where: { dataset: $datasetAddressString }\n        orderBy: timestamp\n        orderDirection: asc\n      ) {\n        dataset {\n          address: id\n        }\n        from {\n          address: id\n        }\n        to {\n          address: id\n        }\n        transaction {\n          txHash: id\n          timestamp\n          blockNumber\n        }\n      }\n    }\n  }\n"): typeof import('./graphql').DatasetDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query NextDatasetDeals(\n    $length: Int = 20\n    $skip: Int = 0\n    $datasetAddress: ID!\n  ) {\n    dataset(id: $datasetAddress) {\n      address: id\n      deals: usages(\n        first: $length\n        skip: $skip\n        orderBy: timestamp\n        orderDirection: desc\n      ) {\n        dealid: id\n      }\n    }\n  }\n"): typeof import('./graphql').NextDatasetDealsDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query Datasets($length: Int = 20, $skip: Int = 0) {\n    datasets(\n      first: $length\n      skip: $skip\n      orderBy: timestamp\n      orderDirection: desc\n    ) {\n      address: id\n      owner {\n        address: id\n      }\n      timestamp\n      name\n      multiaddr\n      checksum\n      transfers(orderBy: timestamp, orderDirection: desc) {\n        transaction {\n          txHash: id\n          timestamp\n          blockNumber\n        }\n      }\n    }\n  }\n"): typeof import('./graphql').DatasetsDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query NextDatasets($length: Int = 20, $skip: Int = 0) {\n    datasets(\n      first: $length\n      skip: $skip\n      orderBy: timestamp\n      orderDirection: desc\n    ) {\n      address: id\n    }\n  }\n"): typeof import('./graphql').NextDatasetsDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query Deal($dealAddress: ID!) {\n    deal(id: $dealAddress) {\n      dealid: id\n      timestamp\n      startTime\n      app {\n        address: id\n        name\n      }\n      dataset {\n        address: id\n        name\n      }\n      workerpool {\n        address: id\n        description\n      }\n      beneficiary {\n        address: id\n      }\n      callback {\n        address: id\n      }\n      appPrice\n      datasetPrice\n      workerpoolPrice\n      params\n      tag\n      trust\n      category {\n        catid: id\n        name\n        workClockTimeRef\n        description\n      }\n      botSize\n      botFirst\n      completedTasksCount\n      claimedTasksCount\n      requester {\n        address: id\n      }\n      dealEvents: events(orderBy: timestamp, orderDirection: asc) {\n        timestamp\n        id\n        type: __typename\n        transaction {\n          txHash: id\n        }\n      }\n    }\n  }\n"): typeof import('./graphql').DealDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query DealTasks($dealAddress: ID!) {\n    deal(id: $dealAddress) {\n      tasks(orderBy: index, orderDirection: asc) {\n        taskid: id\n        index\n        status\n        finalDeadline\n      }\n    }\n  }\n"): typeof import('./graphql').DealTasksDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query Deals($length: Int = 20, $skip: Int = 0) {\n    deals(\n      first: $length\n      skip: $skip\n      orderBy: timestamp\n      orderDirection: desc\n    ) {\n      dealid: id\n      timestamp\n      requester {\n        address: id\n      }\n      beneficiary {\n        address: id\n      }\n      callback {\n        address: id\n      }\n      app {\n        address: id\n      }\n      dataset {\n        address: id\n      }\n      workerpool {\n        address: id\n      }\n      category {\n        catid: id\n        workClockTimeRef\n      }\n      startTime\n      appPrice\n      datasetPrice\n      workerpoolPrice\n      botSize\n      trust\n      completedTasksCount\n      claimedTasksCount\n    }\n  }\n"): typeof import('./graphql').DealsDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query NextDeals($length: Int = 20, $skip: Int = 0) {\n    deals(\n      first: $length\n      skip: $skip\n      orderBy: timestamp\n      orderDirection: desc\n    ) {\n      dealid: id\n    }\n  }\n"): typeof import('./graphql').NextDealsDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query NextTasks($length: Int = 20, $skip: Int = 0) {\n    tasks(\n      first: $length\n      skip: $skip\n      orderBy: timestamp\n      orderDirection: desc\n    ) {\n      taskid: id\n    }\n  }\n"): typeof import('./graphql').NextTasksDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query Tasks($length: Int = 20, $skip: Int = 0) {\n    tasks(\n      first: $length\n      skip: $skip\n      orderBy: timestamp\n      orderDirection: desc\n    ) {\n      taskid: id\n      index\n      finalDeadline\n      status\n      timestamp\n      deal {\n        requester {\n          address: id\n        }\n        beneficiary {\n          address: id\n        }\n        app {\n          address: id\n        }\n        dataset {\n          address: id\n        }\n        workerpool {\n          address: id\n        }\n        category {\n          catid: id\n          workClockTimeRef\n        }\n      }\n    }\n  }\n"): typeof import('./graphql').TasksDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query NextWorkerpools($length: Int = 20, $skip: Int = 0) {\n    workerpools(\n      first: $length\n      skip: $skip\n      orderBy: timestamp\n      orderDirection: desc\n    ) {\n      address: id\n    }\n  }\n"): typeof import('./graphql').NextWorkerpoolsDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query Workerpools($length: Int = 20, $skip: Int = 0) {\n    workerpools(\n      first: $length\n      skip: $skip\n      orderBy: timestamp\n      orderDirection: desc\n    ) {\n      address: id\n      owner {\n        address: id\n      }\n      timestamp\n      description\n      workerStakeRatio\n      schedulerRewardRatio\n      transfers(orderBy: timestamp, orderDirection: desc) {\n        transaction {\n          txHash: id\n          timestamp\n          blockNumber\n        }\n      }\n    }\n  }\n"): typeof import('./graphql').WorkerpoolsDocument;


export function graphql(source: string) {
  return (documents as any)[source] ?? {};
}
